// function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}

  ${data.license!='None'? `![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)`: ""}

  
  ## Description
  --------------
  ${data.description}
  
  ## Table of Contents
  
  - [Description](#Description)
  - [Installation](#Installation)
  - [License](#License)
  - [Usage](#Usage)
  - [Contributing](#Contributing)
  - [Test](#Test)
  - [Questions](#questions)
  
  
  ## Installation
  ---
  ${data.installation}

  
  ## License
  ---
  This application is licensed under:

  ${data.license} license
  
  ## Usage
  ---
  ${data.usage}
  
  ## Contributing
  ---
  ${data.contribute}
  
  ## Test
  ---
  ${data.test}  
  
  
  ## Questions
  ---
  If you have any questions, please feel free to check out my github account and email me at the email address below:
  
  Github account: [${data.github}](https://github.com/${data.github})
  
  Email address: ${data.email}

  _This README was generated by [readme-generator](https://github.com/sistaniabong/readme-generator)_

`;
}

module.exports = {generateMarkdown};
